### ISSUE TITLE
Property binding in "SourceParamter" is ignored

### ISSUE THREAD

**Issue by kebekus** [maplibre/maplibre-native-qt#115]
**Describe the bug**

I use MapLibre with QML. The map contains a source parameter of the following form.

```
        SourceParameter {
            id: approachChart

            styleId: "vac"
            type: "image"

            property string url: expressionA

            property var coordinates: expressionB

        }
```

**Expected behavior**

- The image should change whenever the value of expressionA changes
- The coordinates of the image in the map display should change whenever the value of expressionB changes

**Actual behavior**

- The image changes whenever the value of expressionA changes
- The coordinates of the image never change, regardless of the value of expressionB. The binding for the "coordinates" property is seemingly ignored.

**Platform information (please complete the following information):**

 - OS: macOS and Linux
 - Qt version 6.6.2

**Additional context**

At present, the only way to move the image on the map is to discard the map and construct a new one. This is time-consuming and leads to visible glitches in the display.

@ntadej Let me thank you again for maintaining this marvelous piece of software!

**Comment by ntadej** [comment]
Note that according to my memory not all source properties are mutable even in core MapLibre, but I'll investigate.
