### ISSUE TITLE
CMake target "Core" conflicts with maplibre-native definition

### ISSUE THREAD

**Issue by dpaulat** [maplibre/maplibre-native-qt#118]
**Describe the bug**

[vendor/maplibre-native/CMakeLists.txt Line 39](https://github.com/maplibre/maplibre-native/blob/dd319761d26cd65fd63113a232cabfd4b92561ef/CMakeLists.txt#L39) defines:
`set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER Core)`

This conflicts with the target named "Core", defined in [src/core/CMakeLists.txt ](https://github.com/maplibre/maplibre-native-qt/blob/main/src/core/CMakeLists.txt)

**To Reproduce**
1. Use CMake to Generate a Visual Studio solution (e.g., `cmake -S . -B build-dir -G "Visual Studio 17 2022"`)
2. Open the Visual Studio solution
3. An error appears, stating The solution already contains an item named 'Core'.
4. The Core project does not appear in the solution explorer

**Expected behavior**
All projects appear in the solution explorer.

**Screenshots**
![devenv_UVbYMsXQLx](https://github.com/maplibre/maplibre-native-qt/assets/2886605/1abe6094-7cf1-4cf5-bcdb-93f5681b3cc3)
![image](https://github.com/maplibre/maplibre-native-qt/assets/2886605/86d977af-2f87-4a5a-8f84-24ef84aa2cad)

**Platform information (please complete the following information):**
 - OS: Windows
 - Qt version 6.6.1
 - Version latest

**Additional context**
I've worked around this temporarily by adding `set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER CMakePredefinedTargets)`, reverting to the default value.

Additionally, I'm importing maplibre-native-qt into another project, using CMake's add_subdirectory.  This has worked great for maplibre-native in the past, especially with the "mbgl-" naming prefix for all the projects.  I noticed maplibre-native-qt is using more generic target names like "Core", "Widgets", and "Location".  Has consideration been given to using something like "mln" within the name to ensure uniqueness and reduce the probability of conflict?

**Comment by ntadej** [comment]
Thanks for the report. I'm sorry that I forgot about subdirectory usage. Will try to improve it ASAP.

**Comment by dpaulat** [comment]
Thanks! Not a big hurry, I've been able to work around it.
