### ISSUE TITLE
add icon in map

### ISSUE THREAD

**Issue by Xinyu-HD** [maplibre/maplibre-native-qt#145]
I try to add an image to the map at the specified coordinates using addImage, but the error "Image has to contain an ID." keeps appearing. How can I solve this? I've put the code below.

![image](https://github.com/user-attachments/assets/410bc31f-df36-4fd0-8a47-3bbdfb40aa1b)
![image](https://github.com/user-attachments/assets/021a52e0-9dea-4b9d-a2a0-11c91570c1f6)
![image](https://github.com/user-attachments/assets/14a5f181-7c9d-4366-ba29-b9e8487baf8b)

**Comment by ntadej** [comment]
Please do not open duplicate tickets, it will not solve your issue any faster.

I will try to have a look in the next days, but I am very busy at the moment. What would help is to provide a minimal reproducer so it can also be included as a test. Please do not put code in screenshots but use code blocks instead.
