### ISSUE TITLE
git submodule call under windows: file names too long

### ISSUE THREAD

**Issue by petricf** [maplibre/maplibre-native-qt#157]
**Describe the bug**
Windows platform: During "git submodule ..." got error "filename too long"

**To Reproduce**
1. git clone https://github.com/maplibre/maplibre-native-qt.git
2. cd maplibre-native-qt
3. git submodule update --init --recursive
4. Error

**Expected behavior**
git submodule call to be properly executed

**Screenshots**
> ...
> error: unable to create file output/nested-multi-polygon-outer-counter-clockwise-inner-clockwise-hole-clockwise/-9.83276,36.9411,-8.01453,39.4012,simplify_distance=8,strictly_simple=0,fill_type=0,mpu=0,par=0.geojson: Filename too long
> error: unable to create file output/nested-multi-polygon-outer-counter-clockwise-inner-clockwise-hole-clockwise/-9.83276,36.9411,-8.01453,39.4012,simplify_distance=8,strictly_simple=0,fill_type=0,mpu=0,par=1.geojson: Filename too long
> error: unable to create file output/nested-multi-polygon-outer-counter-clockwise-inner-clockwise-hole-clockwise/-9.83276,36.9411,-8.01453,39.4012,simplify_distance=8,strictly_simple=0,fill_type=0,mpu=1,par=0.geojson: Filename too long
> error: unable to create file output/nested-multi-polygon-outer-counter-clockwise-inner-clockwise-hole-clockwise/-9.83276,36.9411,-8.01453,39.4012,simplify_distance=8,strictly_simple=0,fill_type=0,mpu=1,par=1.geojson: Filename too long
e
> ...

**Platform information (please complete the following information):**
 - OS: Windows 10 (stable as of today)
 - Qt version not relevant at this stage
 - git version: 2.37.1.windows.1

**Additional context**
Partition is of type NTFS

**Comment by ntadej** [comment]
This can be ignored. Will add it to "known issues" section.
