### ISSUE TITLE
Windows: QMake based project under QtCreator

### ISSUE THREAD

**Issue by petricf** [maplibre/maplibre-native-qt#160]
**Describe the bug**
Simple project runs under Linux but fails under Windows.

**To Reproduce**
1. Compile project under Windows
2. Start it inside QtCreator (under cmdline there is not output)
3. Aborted

**Expected behavior**
Working as it runs with the same code under Linux w/o any errors/warnings

**Screenshots**
App output:
> 11:03:36: Starte C:\Projects\mapwidget-test-Desktop_Qt_6_2_2_MSVC2019_64bit-Debug\debug\mapwidget-test.exe...
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
> QWidget: Must construct a QApplication before a QWidget
> 11:03:39: C:\Projects\mapwidget-test-Desktop_Qt_6_2_2_MSVC2019_64bit-Debug\debug\mapwidget-test.exe ist abgestürzt.

Message when running in debugger:
![grafik](https://github.com/user-attachments/assets/78b7797a-5d6c-4834-b99a-c842ae9ce41a)

Traceback when running in debugger:
![grafik](https://github.com/user-attachments/assets/5a35af08-1b42-437f-a47d-d7dd10f04d55)

**Platform information (please complete the following information):**
 - OS: Windows 10 (inside a QEmu VM)
 - Qt version 6.6.3
 - QtCreator 14.0.1 (Windows)
 - QMapLibreQt version 3.0.0 (from GIT)

**Additional context**
This is my first opengl project. It may be that i miss something.

The message "... Please instantiate the QApplication object first ..." from the app output above is only displayed under Windows - not under Linux.

The windows environment is running under Proxmox (qemu vm system).

Here the project:
[demo-map.zip](https://github.com/user-attachments/files/16673486/demo-map.zip)

The *.pro file may have to be changed. This includes the LIBS and INCLUDEPATH variables which point to the QMapLibre installation.

**Comment by ntadej** [comment]
Does qemu have OpenGL acceleration? Do other Qt example apps work fine?

**Comment by petricf** [comment]
Using Proxmox (https://pve.proxmox.com) here which uses qemu as VM server.

Linux VM (here: Linux Mint) supports OpenGL.
Windows 10 VM requires installation of "OpenCL, OpenGL and Vulcan Compatibility Pack" to support OpenGL 3.

Fixes from #173 solved the problem.
