### ISSUE TITLE
Change map settings dynamically

### ISSUE THREAD

**Issue by petricf** [maplibre/maplibre-native-qt#172]
**Is your feature request related to a problem? Please describe.**
Want to change some attributes/styles while map is displayed. For example changing the zoom factor, center position, etc. by an external signal (not keyboard / mouse).
So far i have not spotted a hint on how doing this.

**Describe the solution you'd like**
I have no idea where such a thing to be placed. GLWidget takes the settings at construction time by reference. So it is not changeable after construction of GLWidget.
Maybe by passing Settings instance to instanciated GLWidget.

**Describe alternatives you've considered**
Destroy GLWidget instance and allocate a new one. 

**Additional context**
OS: Linux
Qt version 6.7.3

**Comment by ntadej** [comment]
You can get the `Map` instance using `map()`.

**Comment by petricf** [comment]
Your support is great. That was the hint a needed.

I have some messages in the console output while running inside QtCreator (Linux). Maybe warnings only. I will open a separate issue item on it.

**Comment by TomazJandrok** [comment]
> You can get the `Map` instance using `map()`.

Could you please elaborate this? So If I send mapView.map from QML to C++ I can then cast that QObject* like following?   
```
    QDeclarativeGeoMap* pMap = qobject_cast<QDeclarativeGeoMap* >(mapView);
    QGeoMap* pGeoMap = pMap->map();
    QMapLibre::QGeoMapMapLibre* pMapLibreMap = dynamic_cast<QMapLibre::QGeoMapMapLibre*>(pGeoMap);
```
I also am trying to dynamicaly set paint properties of already loaded layers via `addStyleParameter` of `QMapLibre::QGeoMapMapLibre`, but the map doesn't reflect new loaded style changes.
