### ISSUE TITLE
Test program runs in release mode but not in debug mode

### ISSUE THREAD

**Issue by petricf** [maplibre/maplibre-native-qt#173]
**Describe the bug**
Debug an application inside QtCreator. It aborts directly after start.

**To Reproduce**
1. Open attached project (expects maplibre files in /Qt/Tools/mvc2022_64/maplibre-qt)
2. Select Debug mode
3. Start application "run debug"
4. See error and traceback

**Expected behavior**
The application should run without problems

**Screenshots**
![image](https://github.com/user-attachments/assets/5f997030-18b0-4831-8592-e802bed44a1f)

It is in german. Tells "process stopped, exception occured" (freely translated)

QtCreator traceback:
![image](https://github.com/user-attachments/assets/4275880d-8059-4894-b88e-d6043907cb6e)

**Platform information (please complete the following information):**
 - OS: Windows 10
 - Qt version 6.7.3

**Additional context**
If compiled in release mode it works well. But the application itself can not be debugged then.

Source Code:
[MapLibreOwn.zip](https://github.com/user-attachments/files/17292856/MapLibreOwn.zip)

Sorry - own coding style used.

**Comment by ntadej** [comment]
Do you link properly with the Debug build of MapLibre? It seems like the debugger did not find debug symbols which may indicate you did not link properly. Note that on Windows you usually can not use release libraries with debug builds.

**Comment by petricf** [comment]
Your hint was very helpful. This fact was unknown t o me.

I had to find out why QtCreator links the *.lib to the app instead of the *d.lib when running in debug mode.
The problem is that the used libs at link time are not shown in the compile output. They are placed in a temporary file which is immediately deleted after compilation.

Due i am using qmake i have to extend the *.pro file in this way:
> Debug::LIBS += -lQMapLibreWidgetsd -lQMapLibred
> Release:LIBS += -lQMapLibreWidgets -lQMapLibre

The prefix of Debug/Release makes the difference.

Hope that helps others.
