### ISSUE TITLE
Cannot compile with Qt6.5.0-beta2

### ISSUE THREAD

**Issue by kebekus** [maplibre/maplibre-native-qt#22]
**Describe the bug**

The title says it: any attempt of mine to compile with Qt6.5.0-beta2 ends with an error message. Any help is greatly appreciated!

**To Reproduce**
1. Git clone v2.0.2 or main
2. Run qt-configure-module

**Expected behavior**
The module gets configured and can be built.

**Screenshots**
```
[kebekus@uni-office qt-geoservices-maplibre-gl]$ ~/Software/buildsystems/Qt/6.5.0/gcc_64/bin/qt-configure-module .
'/mnt/storage/buildsystems/Qt/6.5.0/gcc_64/bin/../libexec/qt-cmake-private' '.'
-- The CXX compiler identification is GNU 12.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
CMake Error at /mnt/storage/buildsystems/Qt/6.5.0/gcc_64/lib/cmake/Qt6/QtPluginHelpers.cmake:216 (get_target_property):
  get_target_property() called with non-existent target
  "Qt6::QGeoServiceProviderFactoryMapLibreGLPlugin".
Call Stack (most recent call first):
  CMakeLists.txt:38 (qt_internal_add_plugin)


-- Configuring incomplete, errors occurred!
See also "/home/kebekus/XX/qt-geoservices-maplibre-gl/CMakeFiles/CMakeOutput.log".
CMake Error at /mnt/storage/buildsystems/Qt/6.5.0/gcc_64/lib/cmake/Qt6/QtProcessConfigureArgs.cmake:987 (message):
  CMake exited with code 1.
```

**Platform information (please complete the following information):**
 - OS: Fedora37
 - Qt version 6.5.0-beta2, downloaded with Qt installer

**Comment by kebekus** [comment]
Understood. Thank you for your prompt reply!

**Comment by emericg** [comment]
I'm still hitting the same `get_target_property() called with non-existent target` issue when building with the latest commit for Qt 6.5. It is mentioned on the initial pull request https://github.com/maplibre/maplibre-native-qt/pull/26 that there is a 'fix' available, or something to hard-code to get it working, but I am not fluent enough in CMake to understand it...

Would it be possible to get a bit more info on that issue?
I'm really looking forward to the maplibre-native-qt working with Qt6.5+!

**Comment by ntadej** [comment]
I will open another PR by the end of the week that will have Qt 6.5 fully working (without the parameters at this point). Note that it will not build on mobiles in the first iteration.

**Comment by emericg** [comment]
That's awesome, desktop support would be great to start testing. Thanks for the quick reply!

**Comment by ntadej** [comment]
This issue should be fixed. Please test with the latest `main`. Qt 6.6 support is also coming in #47.

**Comment by kebekus** [comment]
I confirm that this issue is solved now. Thanks for your fantastic work!
