### ISSUE TITLE
The geoservices provider is not supported (Android Qt QML)

### ISSUE THREAD

**Issue by Aashik0808** [maplibre/maplibre-native-qt#28]
W ple.minimal_ma: Unexpected CPU variant for X86 using defaults: x86_64
D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10148; state: DISABLED
D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
V GraphicsEnvironment: ANGLE Developer option for 'org.qtproject.example.minimal_map' set to: 'default'
V GraphicsEnvironment: ANGLE GameManagerService for org.qtproject.example.minimal_map: false
V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
D NetworkSecurityConfig: No Network Security Config specified, using platform default
D NetworkSecurityConfig: No Network Security Config specified, using platform default
D libEGL  : loaded /vendor/lib64/egl/libEGL_emulation.so
W System  : ClassLoader referenced unknown path:
D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
D libEGL  : loaded /vendor/lib64/egl/libGLESv2_emulation.so
D Qt JAVA : Class org.qtproject.qt5.android.positioning.QtPositioning does not implement setActivity method
I QtCore  : Start
I Qt      : qt started
I QtPositioning: Positioning start
D HostConnection: createUnique: call
D HostConnection: HostConnection::get() New Host Connection established 0x7bf9849985d0, tid 10232
D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
W OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
D EGL_emulation: eglCreateContext: 0x7bf98499ab50: maj 3 min 0 rcv 3
D EGL_emulation: eglMakeCurrent: 0x7bf98499ab50: ver 3 0 (tinfo 0x7bfba932b080) (first time)
I Gralloc4: mapper 4.x is not supported
D HostConnection: createUnique: call
D HostConnection: HostConnection::get() New Host Connection established 0x7bf984999f50, tid 10232
D goldfish-address-space: allocate: Ask for block of size 0x100
D goldfish-address-space: allocate: ioctl allocate returned offset 0x3f3ffe000 size 0x2000
W Gralloc4: allocator 4.x is not supported
D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
***D libminimal_map_x86_64.so: 1 ,  "The geoservices provider is not supported".***
D HostConnection: createUnique: call
D HostConnection: HostConnection::get() New Host Connection established 0x7bf98499f350, tid 10242
D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
D EGL_emulation: eglCreateContext: 0x7bf98499d850: maj 3 min 0 rcv 3
D EGL_emulation: eglMakeCurrent: 0x7bf98499d850: ver 3 0 (tinfo 0x7bfba932b100) (first time)
D HostConnection: createUnique: call
D HostConnection: HostConnection::get() New Host Connection established 0x7bf98499d9d0, tid 10304
D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
D EGL_emulation: eglMakeCurrent: 0x7bf98499d850: ver 3 0 (tinfo 0x7bfba932b180) (first time)

**Comment by ntadej** [comment]
Thanks for the issue report. Can you please provide a bit more information:
- Qt version used
- How you installed the library to make sure no mistakes were made

**Comment by Aashik0808** [comment]
Qt Version = 5.15.2
Method used for install:
        Copied Qt folder extracted from [https://github.com/maplibre/maplibre-native-qt/releases/tag/v2.1.0](https://github.com/maplibre/maplibre-native-qt/releases/tag/v2.1.0) directly to my linux Home where Qt is installed

**Comment by ntadej** [comment]
Will have a look, maybe something unexpected broke (I already updated my Android projects to Qt 6, but I use Qt 5 on iOS and Windows).

Can you try maybe an older release?

**Comment by Aashik0808** [comment]
I tried all the Qt5 version and also Qt6.14.3 latest version. Same problem.

**Comment by Aashik0808** [comment]
Sometimes my installation steps may wrong. Can you send me the correct steps?

**Comment by ntadej** [comment]
What you did is expected -> copy files in your Qt installation. Did you use `maplibregl` as the plugin name?

**Comment by Aashik0808** [comment]
Now it is working.
We nee to add `QT+= location positioning network opengl concurrent sql sensors` inside .pro file
