### ISSUE TITLE
Integration with Qt 6.6

### ISSUE THREAD

**Issue by kamilhajdukiewicz** [maplibre/maplibre-native-qt#30]
Hi, are there any plans to support Qt 6.6 in near future?

**Comment by kebekus** [comment]
Same question here. My app [Enroute Flight Navigation](https://github.com/Akaflieg-Freiburg/enroute) depends on maplibre-native-qt, and I am **extremely** happy with its performance. For now, I am, however, stuck with Qt 6.4.2. 

I would be happy to help testing…

**Comment by ntadej** [comment]
Yes, I'm working on it, but I'm slowed down by other commitments, especially as API changes are needed.

**Comment by kebekus** [comment]
@ntadej Thanks for getting back to me so quickly. This is excellent news indeed.

**Comment by ntadej** [comment]
Some features are still missing, but I'm happy that what you need is already there!

**Comment by ntadej** [comment]
As Qt 6.6 should now have the same level of support as Qt 6.5, I'm closing this one.
