### ISSUE TITLE
Can not build on Qt 6.4.3

### ISSUE THREAD

**Issue by petricf** [maplibre/maplibre-native-qt#32]
**Describe the bug**
As documented in README.md i unpack the source archive (v2.1.0) and created a build directory.

**To Reproduce**
1. Unpack source package (v2.1.0) to ~/maplibre
2. Create build directory
3. Execute qt-cmake
4. See error (below)

**Expected behavior**

qt-cmake completes without errors

**Screenshots**
Calling 

    ~/Qt/6.4.3/gcc_64/bin/qt-cmake ../maplibre -GNinja

it gets me following output:

    -- The CXX compiler identification is GNU 12.2.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE  
    -- Performing Test HAVE_STDATOMIC
    -- Performing Test HAVE_STDATOMIC - Success
    -- Found WrapAtomic: TRUE  
    CMake Error at CMakeLists.txt:32 (add_subdirectory):
      The source directory
    
        /home/petric/maplibre/dependencies/maplibre-gl-native
    
      does not contain a CMakeLists.txt file.
    
    
    -- Configuring incomplete, errors occurred!

**Platform information (please complete the following information):**
 - OS: Linux Debian 12 (Bookworm)
 - Qt version 6.4.3 (6.5.2 also) installed via Qt online installer
 - Version 2.1.0

**Additional context**
Subdirectory "dependencies" contains an other directory named "maplibre-gl-native". But this does not contain any files.

What am i missing here ?

**Comment by ntadej** [comment]
You need to init the submodule
```
git submodule update --init --recursive
```

**Comment by petricf** [comment]
Remember: I downloaded the source archive from your releases page !

The command above gives me:

    fatal: not a git repository (or any of the parent directories): .git

Directory listing:

    drwxrwxr-x  8 petric petric 4096 11. Apr 12:47 .
    drwx------ 58 petric petric 4096 28. Aug 11:51 ..
    -rw-rw-r--  1 petric petric  375 11. Apr 12:47 CHANGELOG.md
    -rw-rw-r--  1 petric petric 2669 11. Apr 12:47 CMakeLists.txt
    -rw-rw-r--  1 petric petric  180 11. Apr 12:47 CODE-OF-CONDUCT.md
    drwxrwxr-x  3 petric petric 4096 11. Apr 12:47 dependencies
    drwxrwxr-x  3 petric petric 4096 11. Apr 12:47 examples
    drwxrwxr-x  5 petric petric 4096 11. Apr 12:47 .github
    -rw-rw-r--  1 petric petric    7 11. Apr 12:47 .gitignore
    -rw-rw-r--  1 petric petric  144 11. Apr 12:47 .gitmodules
    drwxrwxr-x  2 petric petric 4096 11. Apr 12:47 LICENSES
    -rw-rw-r--  1 petric petric  232 11. Apr 12:47 maplibregl_plugin.json
    -rw-rw-r--  1 petric petric 1468 11. Apr 12:47 maplibregl.pro
    -rw-rw-r--  1 petric petric  299 11. Apr 12:47 .qmake.conf
    -rw-rw-r--  1 petric petric 1194 11. Apr 12:47 README.md
    drwxrwxr-x  2 petric petric 4096 11. Apr 12:47 resources
    drwxrwxr-x  2 petric petric 4096 11. Apr 12:47 src
    -rw-rw-r--  1 petric petric    6 11. Apr 12:47 VERSION.txt

**Comment by ntadej** [comment]
Ah, that's a good observation. Then I guess we'll have to start providing custom source distributions. For now you'll unfortunately have to use git. I will try to upload the tarball for the latest release ASAP.

**Comment by petricf** [comment]
If the "git submodule ..." command is still required i suggest to add it to README.md

**Comment by ntadej** [comment]
Full source tarball is now provided and submodules are mentioned in the documentation.
