### ISSUE TITLE
Build from Git failed

### ISSUE THREAD

**Issue by petricf** [maplibre/maplibre-native-qt#33]
**Describe the bug**
Build from Git failed. Tried it as result of bug #32

**To Reproduce**
1. git clone https://github.com/maplibre/maplibre-native-qt.git
2. cd maplibre-native-qt && git submodule update --init --recursive
3. mkdir ~/maplibre-build && cd ~/maplibre-build
4. ~/Qt/6.4.3/gcc_64/bin/qt-cmake ../maplibre-native-qt -GNinja
5. ninja
6. Error at link step of libqtgeoservices_maplibregl.so (see below)

**Expected behavior**
Compiles and links the code.

**Screenshots**

Log of the linkage errors:

    [407/407] Linking CXX shared module plugins/geoservices/libqtgeoservices_maplibregl.so
    FAILED: plugins/geoservices/libqtgeoservices_maplibregl.so 
    : && /usr/bin/c++ -fPIC -g -DNDEBUG -O2  -Wl,--no-undefined -Wl,--enable-new-dtags -shared  -o plugins/geoservices
    
    ...
    
    /mbgl-vendor-nunicode.dir/vendor/nunicode/src/libnu/toupper.c.o QMapLibreGL/CMakeFiles/mbgl-vendor-nunicode.dir/vendor/nunicode/src/libnu/utf8.c.o QMapLibreGL/CMakeFiles/mbgl-vendor-csscolorparser.dir/vendor/csscolorparser/csscolorparser.cpp.o CMakeFiles/QGeoServiceProviderFactoryMapLibreGLPlugin.dir/QGeoServiceProviderFactoryMapLibreGLPlugin_autogen/mocs_compilation.cpp.o CMakeFiles/QGeoServiceProviderFactoryMapLibreGLPlugin.dir/src/qgeoserviceproviderpluginmaplibregl.cpp.o CMakeFiles/QGeoServiceProviderFactoryMapLibreGLPlugin.dir/src/qgeomappingmanagerenginemaplibregl.cpp.o CMakeFiles/QGeoServiceProviderFactoryMapLibreGLPlugin.dir/src/qgeomapmaplibregl.cpp.o CMakeFiles/QGeoServiceProviderFactoryMapLibreGLPlugin.dir/src/qmaplibreglstylechange.cpp.o CMakeFiles/QGeoServiceProviderFactoryMapLibreGLPlugin.dir/src/qsgmaplibreglnode.cpp.o CMakeFiles/QGeoServiceProviderFactoryMapLibreGLPlugin.dir/qrc_maplibregl.cpp.o  -Wl,-rpath,/home/petric/Qt/6.4.3/gcc_64/lib:  /usr/lib/x86_64-linux-gnu/libxkbcommon.so  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6Location.so.6.4.3  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6PositioningQuick.so.6.4.3  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6Positioning.so.6.4.3  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6Quick.so.6.4.3  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6OpenGL.so.6.4.3  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6QmlModels.so.6.4.3  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6Qml.so.6.4.3  -lz  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6Sql.so.6.4.3  /home/petric/Qt/6.4.3/gcc_64/lib/libicuuc.so  -ldl  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6Network.so.6.4.3  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6Gui.so.6.4.3  /usr/lib/x86_64-linux-gnu/libGL.so  /home/petric/Qt/6.4.3/gcc_64/lib/libQt6Core.so.6.4.3  -Wl,-rpath-link,/home/petric/Qt/6.4.3/gcc_64/lib && cd /home/petric/maplibre-build && /usr/bin/objcopy --only-keep-debug /home/petric/maplibre-build/plugins/geoservices/libqtgeoservices_maplibregl.so /home/petric/maplibre-build/plugins/geoservices/qtgeoservices_maplibregl.debug && /usr/bin/objcopy --strip-debug /home/petric/maplibre-build/plugins/geoservices/libqtgeoservices_maplibregl.so && /usr/bin/objcopy --add-gnu-debuglink=/home/petric/maplibre-build/plugins/geoservices/qtgeoservices_maplibregl.debug /home/petric/maplibre-build/plugins/geoservices/libqtgeoservices_maplibregl.so && chmod -x /home/petric/maplibre-build/plugins/geoservices/qtgeoservices_maplibregl.debug
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDiImpl::BiDiImpl()':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:15: undefined reference to `ubidi_open_72'
    /usr/bin/ld: /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:15: undefined reference to `ubidi_open_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDiImpl::~BiDiImpl()':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:18: undefined reference to `ubidi_close_72'
    /usr/bin/ld: /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:19: undefined reference to `ubidi_close_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDi::mergeParagraphLineBreaks(std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> >&)':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:58: undefined reference to `ubidi_countParagraphs_72'
    /usr/bin/ld: /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:62: undefined reference to `ubidi_getParagraphByIndex_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::applyArabicShaping(std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> > const&)':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:35: undefined reference to `u_shapeArabic_72'
    /usr/bin/ld: /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:45: undefined reference to `u_shapeArabic_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDi::writeReverse(std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> > const&, unsigned long, unsigned long)':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:192: undefined reference to `ubidi_writeReverse_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDi::getLine[abi:cxx11](unsigned long, unsigned long)':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:210: undefined reference to `ubidi_setLine_72'
    /usr/bin/ld: /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:219: undefined reference to `ubidi_getProcessedLength_72'
    /usr/bin/ld: /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:225: undefined reference to `ubidi_writeReordered_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDi::processText(std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> > const&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> >)':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:96: undefined reference to `ubidi_setPara_72'
     /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDi::processStyledText(std::pair<std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> >, std::vector<unsigned char, std::allocator<unsigned char> > > const&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> >)':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:113: undefined reference to `ubidi_setPara_72'
    /usr/bin/ld: /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:129: undefined reference to `ubidi_setLine_72'
    /usr/bin/ld: /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:135: undefined reference to `ubidi_countRuns_72'
    /usr/bin/ld: /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:143: undefined reference to `ubidi_getVisualRun_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDi::mergeParagraphLineBreaks(std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> >&)':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:65: undefined reference to `u_errorName_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDi::writeReverse(std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> > const&, unsigned long, unsigned long)':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:200: undefined reference to `u_errorName_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDi::getLine[abi:cxx11](unsigned long, unsigned long)':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:213: undefined reference to `u_errorName_72'
    /usr/bin/ld: /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:234: undefined reference to `u_errorName_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o: in function `mbgl::BiDi::processText(std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> > const&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> >)':
    /home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:100: undefined reference to `u_errorName_72'
    /usr/bin/ld: QMapLibreGL/CMakeFiles/mbgl-core.dir/platform/default/src/mbgl/text/bidi.cpp.o:/home/petric/maplibre-native-qt/dependencies/maplibre-gl-native/platform/default/src/mbgl/text/bidi.cpp:131: more undefined references to `u_errorName_72' follow
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.

**Platform information (please complete the following information):**
 - OS: Linux Debian 12
 - Qt version 6,4.3
 - Version Git main

**Additional context**

On request i can send the output of the last 157 lines (screen buffer). There are some compile warnings also.

**Comment by ntadej** [comment]
Seems ICU related which was fixed with #56. Please reopen if other issues are present.
