### ISSUE TITLE
Improve handling of ICU on Linux

### ISSUE THREAD

**Issue by ntadej** [maplibre/maplibre-native-qt#39]
Only Linux uses ICU for bidirectional text (and related functionality). This causes issues with building. While we should keep compatibility with Qt binaries we should also make it easier for distribution users:
- [x] Make sure that internal ICU is not used when not selected.
- [ ] Test builds with internal ICU and the effect on size.
- [ ] Make sure that Qt6 binaries are still compatible.

/cc @petricf @emericg

**Comment by ntadej** [comment]
ICU handling has been improved with #56 so now there should be no build issues. More investigation still needs to be done though.

**Comment by emericg** [comment]
I tested this with Qt 6.6 (linux, and android as well too actually, works very well).
The internal ICU usage is only adding about 300 kb to libQMapLibre (out of 11.2-5 mb) and both internal or system ICU builds are working.
