### ISSUE TITLE
QT 6.5.3 Linux symbol lookup error

### ISSUE THREAD

**Issue by wecand0** [maplibre/maplibre-native-qt#70]
I installed this project to `/home/user/Qt/6.5.3/gcc_64`

Try to compile example with widjets, the error is `symbol lookup error: /lib/x86_64-linux-gnu/libQt6OpenGL.so.6: undefined symbol: _ZNK14QWindowPrivate12shareContextEv, version Qt_6_PRIVATE_API`
How to fix it? In general QT works under clion from my Qt folder(I installed all default plugins from qt online installer)
OS: Mint 21.2
IDE: the latest CLion

My cmake:

```
cmake_minimum_required(VERSION 3.24)
project(untitled)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)


set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

set(CMAKE_PREFIX_PATH "/home/user/Qt/6.5.3/gcc_64")

find_package(Qt6 COMPONENTS
        Core
        Gui
        Widgets
        OpenGLWidgets
        REQUIRED)

qt_standard_project_setup()

find_package(QMapLibre COMPONENTS Widgets REQUIRED)

add_executable(untitled main.cpp mainwindow.cpp mainwindow.hpp window.cpp window.hpp)

target_link_libraries(untitled PRIVATE
        Qt6::OpenGLWidgets
        Qt::Core
        Qt::Gui
        Qt::Widgets
        QMapLibre::Widgets
        )

```

**Comment by FinitelyFailed** [comment]
I got a similar issue with symbol lookup error, but with libsqlite instead.
`./QMapLibreExampleQuick: symbol lookup error: <homedir>/Qt6/6.5.3/gcc_64/plugins/sqldrivers/libqsqlite.so: undefined symbol: _ZN10QSqlDriverC2ER17QSqlDriverPrivateP7QObject, version Qt_6_PRIVATE_API`

The program starts when I move "libqsqlite.so" to some other dir. But then I get a lot of "[ WARNING ]  "{unknown}[Database](14): Can't write resource: SQLite driver not found."".

**Comment by ntadej** [comment]
`LD_LIBRARY_PATH`, `QML_IMPORT_PATH` and `QT_PLUGIN_PATH` are now referenced in the documentation.
