### ISSUE TITLE
Static build

### ISSUE THREAD

**Issue by wecand0** [maplibre/maplibre-native-qt#77]
I want to have statically build application. I have qt static build, before in maplibre-native there was flag for static build MBGL_QT_STATIC in https://github.com/maplibre/maplibre-native/blob/qt-v2.0.1/platform/qt/qt.cmake
Is it possible to add this feature?
Thanks for any replays!

**Comment by ntadej** [comment]
If you build with Qt 6 the detection should be automatic (although full CMake support is still WIP).

For Qt 5 this will be re-added in the future.

**Comment by wecand0** [comment]
I use qt6.5.3, there is an issue (warning) in cmake also `CMake Error: install(EXPORT "QMapLibreLocationPluginGeoServicesTargets" ...) includes target "qtgeoservices_maplibre" which requires target "qtgeoservices_maplibre_init" that is not in any export set.`
