### ISSUE TITLE
Linker problems with iOS

### ISSUE THREAD

**Issue by kebekus** [maplibre/maplibre-native-qt#89]
Dear Tadej, dear all,

over the last few days, I managed to get maplibre-native-qt work under Android, Linux, macOS and finally iOS. The software works wonderfully, thank you all for your phantastic work.

While everything worked out of the box on Android, Linux and macOS, I had a really hard time to get iOS to work.

- maplibre-native-qt compiles fine (current main branch)
- It took me a while to figure out that I had to link my app against QMapLibre::PluginGeoServices to get the maplibre plugin.
- Once I tried to link to the static plugin, I found that symbols were missing for csscolorparser, nunicode and parsedate. I solved the problem by copying the relevant source files to my app, but that is probably not the intended way that things should work...

I understand that maybe I should have waited to an official version of your software to appear, but patience has never been my strong point.

Best wishes and Merry Christmas to all of you,

Stefan.

**Comment by ntadej** [comment]
If you use CMake, the easiest way to have consistent setup is to use
```
qmaplibre_location_setup_plugins(<your_target>)
```

The static linking should be fixed with #90.

**Comment by kebekus** [comment]
@ntadej Thanks for the extremely prompt reply during the holidays. I can confirm that qmaplibre_location_setup_plugins() works fine. I will come back to the linker issue as soon as your PR is merged. Thanks again!

**Comment by kebekus** [comment]
@ntadej I can confirm that the static linking issues are with https://github.com/maplibre/maplibre-native-qt/pull/90. Thanks!
