### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by rinigus** [maplibre/maplibre-native-qt#92]
As v2.1.0 cannot be used with Qt5, would you mind to tag current state as a new release? I have used 85673cbe94d6ec0d9e7a35952375c24cb5f51589 for testing on Sailfish OS and it looks to be working fine. Had to adjust QML bindings (https://github.com/rinigus/mapbox-gl-qml) for updated API, but that seemed to work without any issues. Would be great to release updated libs stack for use on mobile Linux platforms.

**Comment by ntadej** [comment]
Interesting, I use v2.1.0 in production Qt5-based apps.

I will tag v3 as soon as I get the automated builds for Windows running (in the next few days).

**Comment by rinigus** [comment]
I wonder if you are using qmake then. As I don't see how the following line can work in the systems without Qt6:

https://github.com/maplibre/maplibre-native-qt/blob/57bf1a38ac12023d9454d27aebba7604d357d2ad/CMakeLists.txt#L15

**Comment by ntadej** [comment]
Yes, Qt5 build of v2 needs to be built with qmake.

**Comment by rinigus** [comment]
OK, so that was a lost functionality when compared to building maplibre-native. I guess I will wait for new release instead of changing building scripts for SFOS

**Comment by birkskyum** [comment]
https://github.com/maplibre/maplibre-native-qt/issues/92#issuecomment-1875229263

> I will tag v3 as soon as I get the automated builds for Windows running (in the next few days).

The Windows CI appear to pass for both qt 5 and qt 6 on main. Did the scope of the v3 release increase?

**Comment by ntadej** [comment]
No, but I still need to test it for all platforms, but I'm getting there.

**Comment by ntadej** [comment]
With many delays, 3.0 will be released imminently!
