### ISSUE TITLE
Unused parameter in Map::addLayer

### ISSUE THREAD

**Issue by nunojpg** [maplibre/maplibre-native-qt#93]
https://github.com/maplibre/maplibre-native-qt/blob/85673cbe94d6ec0d9e7a35952375c24cb5f51589/src/core/map.cpp#L1051

Parameter `id` in Map::addLayer is actually unused except for the error message, I assume this was a mistake during the refactor where  the parameter was introduced.

**Comment by rinigus** [comment]
That parameter was absent in the earlier versions. Good catch.

**Comment by ntadej** [comment]
The idea was to unify the API and was proposed during the review. I guess to do it properly the ID needs to be split out of params and passed separately.
